version: 2.1

orbs:
    continuation: circleci/continuation@0.1.2
    slack: circleci/slack@3.4.2
    jq: circleci/jq@2.2.0
jobs:
    test:
        docker:
            - image: rishabhpoddar/supertokens_python_driver_testing
        environment:
            MOCHA_FILE: ../supertokens-auth-react/test_report/report_node-<< parameters.fdi-version >>.xml
        parameters:
            fdi-version:
                type: string
        parallelism: 4
        steps:
            - checkout
            - attach_workspace:
                  at: /
            - run: echo "127.0.0.1 localhost.org" >> /etc/hosts
            - run: make with-fastapi
            - run: (cd .circleci && ./authReactFastApi.sh << parameters.fdi-version >>)
            - run: ls -la ../supertokens-auth-react/test_report || true
            - store_test_results:
                  path: ../supertokens-auth-react/test_report/report_node-<< parameters.fdi-version >>.xml
            - store_artifacts:
                  path: ../supertokens-auth-react/test_report/screenshots
                  destination: failed-test-screenshots
            - store_artifacts:
                  path: ../supertokens-auth-react/test_report/logs
                  destination: logfiles

workflows:
    version: 2
    tagged-build:
        jobs:
            - test:
                  filters:
                      branches:
                          only: auth-react-tests-parallel
                  matrix:
                      parameters:
                          fdi-version: placeholder
