name: "Code formatting check"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-title:
        name: Code formatting check
        runs-on: ubuntu-latest
        container: rishabhpoddar/supertokens_python_driver_testing
        steps:
            - uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                node-version: '12'
            - run: git init && git add --all && git -c user.name='test' -c user.email='test@example.com' commit -m 'init for pr action'
            - run: make dev-install
            - run: make format
            - run: exit $(git ls-files . --exclude-standard --others -m | wc -l)
             