name: "Code typing check"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-title:
        name: Type check
        runs-on: ubuntu-latest
        container: rishabhpoddar/supertokens_python_driver_testing
        steps:
            - uses: actions/checkout@v2
            - name: Set up node
              uses: actions/setup-node@v1
              with:
                node-version: '12'
            - run: make dev-install
            - run: make check-lint
             